isProduction: false
database:
  deploy: true
  image:
    repository: postgres
    tag: latest
  name: database-deployment
  namespace: database-tech-challenge
  port: 5432
  envSecretName: database-secret
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 3
  volumeMount:
    mountPath: /var/lib/postgresql/data
    name: database-pvc
  podName: database-pod
  serviceName: database-service
  nodePort: 31000 
monitoring:
  namespace: monitoring-tech-challenge
  prometheus:
    deploy: true
    replicas: 1
    configMpName: prometheus-configmap
    image:
      repository: prom/prometheus
      tag: latest
    deployment:
      name: prometheus-deployment
      spec:
        podName: prometheus-pod
        port: 9090
        volumeMount:
          mountPath: /etc/prometheus
          name: prometheus-volume
    service:
      name: prometheus-service
      type: NodePort
      nodePort: 31003