isProduction: true
database:
  deploy: false
monitoring:
  namespace: monitoring-tech-challenge
  prometheus:
    deploy: true
    replicas: 1
    configMpName: prometheus-configmap
    image:
      repository: prom/prometheus
      tag: latest
    deployment:
      name: prometheus-deployment
      spec:
        podName: prometheus-pod
        port: 9090
        volumeMount:
          mountPath: /etc/prometheus
          name: prometheus-volume
    service:
      name: prometheus-service
      type: LoadBalancer
      nodePort: 31003
      protocolTCP: true
  grafana:
    deploy: true
    replicas: 1
    pvcName: grafana-pvc
    image:
      repository: grafana/grafana
      tag: 8.1.5
    deployment:
      name: grafana-deployment
      spec:
        podName: grafana-pod
        port: 3000
        volumeMount:
          mountPath: /var/lib/grafana
          name: grafana-volume
    service:
      name: grafana-service
      type: LoadBalancer
      nodePort: 31002
      protocolTCP: true
api:
    namespace: api-tech-challenge
    replicas: 2
    envSecretName: api-secrets
    image:
      repository: gustavoclemente/api-tech-challenge-fiap
      tag: 1.1.0
    deployment:
      name: api-fiap-deployment
      spec:
        podName: api-fiap-pod
        port: 3000
      livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 30
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 500m
    service:
      name: api-service
      type: LoadBalancer
      nodePort: 31001
      protocolTCP: true
    hpa:
      spec:
        scaleTargetRef:
          minReplicas: 2
          maxReplicas: 10
        metrics:
          averageUtilization: 20
volume:
  storageClassname: efs-sc
  efsID: fs-0f7393ad48e2a4c83