{{- if .Values.monitoring.prometheus.deploy | default false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.monitoring.prometheus.configMpName }}
  namespace: {{ .Values.monitoring.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "nestjs-api-metrics"
        metrics_path: /metrics
        static_configs:
          - targets: ["api-service.api-tech-challenge:3000"]
{{- end }}
    