{{- if .Values.monitoring.grafana.deploy | default false }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.monitoring.grafana.pvcName }}
  namespace: {{ .Values.monitoring.namespace }}
annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.volume.storageClassname }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
  {{- if .Values.isProduction }}
  storageClassName: {{ .Values.volume.storageClassname }}
  {{- else }}
  volumeMode: Filesystem
  selector:
    matchLabels:
      app: local-pv
  {{- end }}
{{- end }}