apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.grafana.service.name }}
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: {{ .Values.monitoring.grafana.service.name }}
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  selector:
    app: {{ .Values.monitoring.grafana.deployment.spec.podName }}
  ports:
      - port: {{ .Values.monitoring.grafana.deployment.spec.port }}
        targetPort: {{ .Values.monitoring.grafana.deployment.spec.port }}
        {{- if eq .Values.monitoring.grafana.service.type "NodePort" }}
        nodePort: {{ .Values.monitoring.grafana.service.nodePort }}
        {{- end }}