{{- if .Values.database.deploy | default false }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.volumeMount.name }}
  namespace: {{ .Values.database.namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
{{- end }}