{{- if .Values.database.deploy | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: database-secret 
  namespace: {{ .Values.database.namespace }}
data:
  POSTGRES_DB: {{ .Values.DB_DATABASE | b64enc | quote }}
  POSTGRES_USER: {{ .Values.DB_USERNAME | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.DB_PASSWORD | b64enc | quote }}
  POSTGRES_HOST: {{ .Values.DB_HOST | b64enc | quote }}
{{- end }}