{{- if .Values.database.deploy | default false }}
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: {{ .Values.database.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.database.podName }}
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
      nodePort: {{ .Values.database.nodePort }}
{{- end }}