apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: {{ .Values.api.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.api.deployment.name }}
  minReplicas: {{ .Values.api.hpa.spec.scaleTargetRef.minReplicas }}
  maxReplicas: {{ .Values.api.hpa.spec.scaleTargetRef.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.hpa.spec.metrics.averageUtilization }}
