apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.envSecretName }}
  namespace: {{ .Values.api.namespace }}
data:
  NODE_ENV: {{ ternary "production" "development" .Values.isProduction | b64enc | quote}}
  PROMETHEUS_ENDPOINT: {{ "http://{{ .Values.monitoring.prometheus.service.name }}.{{ .Values.monitoring.namespace }}:{{ .Values.monitoring.prometheus.deployment.spec.port }}" | b64enc | quote }}
  DB_DATABASE: {{ .Values.DB_DATABASE | b64enc | quote }}
  DB_USERNAME: {{ .Values.DB_USERNAME | b64enc | quote }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD | b64enc | quote }}
  DB_HOST: {{ ternary 
    (printf "%s.%s" .Values.database.serviceName .Values.database.namespace)
    .Values.DB_HOST  
    .Values.database.deploy | b64enc | quote
  }}