apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  namespace: {{ .Values.api.namespace }}
  labels:
    app: {{ .Values.api.service.name }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ .Values.api.deployment.spec.podName }}
  ports:
      - port: {{ .Values.api.deployment.spec.port }}
        targetPort: {{ .Values.api.deployment.spec.port }}

        {{- if eq .Values.api.service.type "NodePort" }}
        nodePort: {{ .Values.api.service.nodePort}}
        {{- end }}

        {{- if .Values.api.service.protocolTCP }} 
        protocol: TCP
        {{- end }}